import DogWalkingHeader from '../images/dog-walking-header.png'
import DogTreatsHeader from '../images/dog-treats-header.png'
import DogHiking from '../images/dog-hiking-header.png'

const blogContent = [

    {title: "Teach your dog to walk on a loose leash!",
    description: "Everyone has issues with walking their dog at first, but that doesn't mean it has to become a regular occurrence! With a few simple tips and tricks, you can have your dog walking like a pro in no time!",
    date: "November 5, 2021",
    author: "Taylor Miller",
    image: DogWalkingHeader, 
    p1: "If you’ve ever had a dog that has pulled during walks (and let’s face it, that’s probably most of us), then you know full well just how unpleasant the outings can be. I have been dragged down hills by dogs, tripped over dogs, and have hurt my back at sudden lunges. After working with my trainer, Ruben of Kindred Dog PDX, I learned a ton of super helpful loose leash walking tips that have changed the way I think about dog walks. After several weeks of dedicated work, Sitka is great on leash and I know how to manage him in various situations. Teaching a dog to walk nicely on a leash requires patience and committment. It is a monotonous process that involves redefining what it means to walk with your dog. As tedious as the process is, it is temporary and the end result will make you swell with pride.",
    p2: "Loose leash walking means that your dog is walking by your side and not pulling on the leash at any time during your walk. So many owners expect dogs to just know how to walk on leash out of the box, but unfortunately, that is not the case.",
    p3: "There are so many stimuli luring them in all sorts of directions like, dogs, noises, people, smells, marking opportunities, etc. Teaching loose leash walking not only makes walks more enjoyable, but also serves as a platform for building and eliminating many other essential skills and behaviors, such as:",
    p4: "This all depends on how dedicated and how consistent you are with the training. I’ve been working with Sitka for about two months and we can go on normal walks for the most part. We’re still working on leash reactivity to other dogs and loud vehicles, as well as distractions by other furry creatures like cats and bunnies, but the majority of our walks are pretty perfect. This came after thrice daily 20-min walks, spaced out throughout the day. In between walks, Sitka was either in his kennel or in “place” on his cot. Trust me when I tell you that these walks were plenty to tire him out for the day. We didn’t run. We didn’t hike. We didn’t play with other dogs. We did these three very mentally challenging walks daily and he was pooped. Focusing on ignoring other distractions and following the handler’s lead is very mentally draining. Think about when you drive in bad weather versus a sunny day. By the time you reach your destination, you are socked.",
    p5: "Mix a handful of high value treats and other not-quite-as-exciting-but-still-enjoyable-treats in with your dog’s food. This will keep them anticipating the arrival of the extra fun treat and will also give you the opportunity to reward your dog big when they do something that makes you extra proud. Rather than feed your dog their meals in their bowl, feed them throughout the day during your training sessions. This will make them more eager to please. If you feed raw, you can get a Goo Toob and fill it with their meals. Just squeeze out a small amount as a treat. I personally use a prong and e-collar (and will be publishing more content on that soon) to train Sitka. I find these tools allow me to better communicate with him, opposed to a traditional flat collar or relying on treats alone. If you do not wish to use a prong and e-collar at this point, use what you are comfortable with, however I do not recommend the use of: Harnesses – I do not find that they allow effective communication between handler and dog. They are also designed for pulling, (yes, even the “no pull” harnesses) and this is the exact behavior we are trying to combat."
},

    {title: "My Favorite Treats!",
    description: 
    "Everyone wants to make sure their dogs are healthy and happy right? Well that is why it is so important to make sure you are feeding your dog treats that are healthy for them! They needs to eat just as well as we do sometimes, so here are some of my favorite healthy treats!",
    date: "November 20, 2021",
    author: "Oakley Miller",
    image: DogTreatsHeader,
    p1: "If you are a dog owner and wanting the best for your dog but cant afford high content dog food (typically extremely expensive), this might well be the perfect solution. A recent survey of dog owners about the “health benefits and health inconveniences of Raw meat-based diets for dogs” came up with some very interesting results. If you want to feed your dog better, but shy away from a full raw meat dog diet … this news will give you the confidence to really boost your dog’s nutrition and health. In the previous blog we discussed the Benefits raw feeders gave about feeding raw dog diets, and how Meat based dog treats can even benefit dogs and owners more. That was an easy task, but many dog owners are even more concerned with the potential downsides of feeding animal products for their dogs?  Much of what you read in the mass media is intentional misinformation, so that is why we look at what actual read feeders are saying and how to OVERCOME any possible negatives. We look at how to overcome any potential downsides those raw feeding owners report about raw diets and how healthy meat based dried dog treats can overcome these issues.  And why grain or vegetable dog treats are a waste of your time and money, literally.",
    p2: "These issues were found to be the second and third highest ‘inconveniences’ suffered by these owner’s dogs. And while these conditions are serious if long term, short term they can be managed by adding more fibre, pro-biotics etc, even charcoal biscuits can assist. But its far better to understand what is going on causing these conditions. You should also note that almost ALL commercial dog food companies suggests that you transition from a competitor product (wet or dry) to theirs over a week to prevent loose stools. This should indicate to a commercial dog food feeder, that even in that ‘perfect world’ that changes of diet are highly likely to cause stress on the digestive system of dogs. The reason that domestic dogs get loose stools or blocked doesn’t have to be from pathogen load, but sometimes are connected with an allergy or even something as simple as changing the proportions of the meat/ offal/ bone mix. And here is something you really need to consider.  As a human, wouldn’t you would hate eating the same meal EVERY NIGHT of your life? But that is exactly what commercial dog food companies tell you to do with your dog, or you risk loose stools!  Dogs in the wild would NOT eat the exact same thing EVERY DAY, so that concept is extremely absurd and dangerous. This means that until a dogs system gets used to variety, different proteins (from single ingredient food or dog treats preferably), they might experience some natural loose stools. The fact that a big part of many pellet/ kibble seller’s game is to provide so much grain that your dog’s stools are extremely consistent (like a fast-food franchise) and easy to pick up. This might make you think that the convenience factor in many commercial dog foods is much higher than their desire to provide the ultimate nutrition, and you would be right.  Because if nutrition was purely the priority your dog would be getting 80% plus meat and animal products and not the usual 30% meat. And they would NOT be getting 30 to 40 ingredients you typically see in commercial dog food to make up for what that grain or vegetable meal lacks.",
    p3: "Prolonged loose stools in any animal is bad as it reduces the health of the intestine and its ability to extract nutrients.  This is where healthy meat-based dog treats can come into play. If your dog is NOT allergic to a meat, and you buy one of our many SINGLE INGREDIENT dog treats, then you know that diarrhea or constipation should not be caused by that treat.  You know that they are going to get a big easy to digest protein boost from the treat. AND the bonus, that properly dried healthy meat-based dog treats provide OVER raw meat, is the much lower possible pathogen load. The heating process basically kills virtually all of the extremely bad bacteria. This is one of the main reasons that many people prefer meat-based treats over raw meat diets. They get to provide the nutrition as well as playing it very safe with their dog. Dog Owners also know that their dog already gets about 70% vegetable matter in their commercial dog food, so adding more vegetable or grain based dog treats DO NOT provide any additional nutrition to their dog. They just look pretty to the owner. Glazed ‘doggy donut’ anyone? Absurd. The grain based treats also are likely to have a whole swathe of additives including sugar, salt, added oils, colouring or preservatives.  Whereas SINGLE ingredient properly dried healthy dog treat is SINGLE INGREDIENT and hence no additives that the dog can react badly to.",
    p4: "This equates to about 10% of the raw meat dog food feeder owners experiencing dog vomiting from time to time. Or maybe even just once. Dogs can vomit for a myriad of reasons, and in fact one of the deadliest common food related deaths is from BLOAT when dogs eat too many pellets and they swell up in the dog’s stomach essentially choking them. A raw diet or meat-based dog treats DON’T swell in size when you add water so they wont cause bloat.  The raw feeders vomiting might be from a pathogen load on meat if it was stored incorrectly. Sometimes dogs will vomit on raw because the fat content of the food was too high. But you can get that in commercial dog food too. Whatever the reason, most meat-based treat feeders report a low vomiting incidence to us. That might be because they value the treat and their dog and restrict how much the dog eats in one session, or they are sure that their dog is not allergic to the treat, or that the treat has been cooked and has a very low chance of pathogen issues. Any way you look at it, vomiting should NOT be increased by cooking meat used in treats. If your dog vomits it is often from enjoying and eating the treat too fast. However, that rare chance is typically far outweigh by the increased nutrient value they get in meat treats (quality amino acids).",
    },

    {title: "Our Favorite Places to Hike!",
    author: "Matthew Miller",
    date: "November 12, 2021",
    description: "Have you ever wanted to take your dog for a mountain hike but didn't quite know where to go? Well here is a short list of fun places!",
    image: DogHiking,
    p1: "If you are a dog owner and wanting the best for your dog but cant afford high content dog food (typically extremely expensive), this might well be the perfect solution. A recent survey of dog owners about the “health benefits and health inconveniences of Raw meat-based diets for dogs” came up with some very interesting results. If you want to feed your dog better, but shy away from a full raw meat dog diet … this news will give you the confidence to really boost your dog’s nutrition and health. In the previous blog we discussed the Benefits raw feeders gave about feeding raw dog diets, and how Meat based dog treats can even benefit dogs and owners more. That was an easy task, but many dog owners are even more concerned with the potential downsides of feeding animal products for their dogs?  Much of what you read in the mass media is intentional misinformation, so that is why we look at what actual read feeders are saying and how to OVERCOME any possible negatives. We look at how to overcome any potential downsides those raw feeding owners report about raw diets and how healthy meat based dried dog treats can overcome these issues.  And why grain or vegetable dog treats are a waste of your time and money, literally.",
    p2: "These issues were found to be the second and third highest ‘inconveniences’ suffered by these owner’s dogs. And while these conditions are serious if long term, short term they can be managed by adding more fibre, pro-biotics etc, even charcoal biscuits can assist. But its far better to understand what is going on causing these conditions. You should also note that almost ALL commercial dog food companies suggests that you transition from a competitor product (wet or dry) to theirs over a week to prevent loose stools. This should indicate to a commercial dog food feeder, that even in that ‘perfect world’ that changes of diet are highly likely to cause stress on the digestive system of dogs. The reason that domestic dogs get loose stools or blocked doesn’t have to be from pathogen load, but sometimes are connected with an allergy or even something as simple as changing the proportions of the meat/ offal/ bone mix. And here is something you really need to consider.  As a human, wouldn’t you would hate eating the same meal EVERY NIGHT of your life? But that is exactly what commercial dog food companies tell you to do with your dog, or you risk loose stools!  Dogs in the wild would NOT eat the exact same thing EVERY DAY, so that concept is extremely absurd and dangerous. This means that until a dogs system gets used to variety, different proteins (from single ingredient food or dog treats preferably), they might experience some natural loose stools. The fact that a big part of many pellet/ kibble seller’s game is to provide so much grain that your dog’s stools are extremely consistent (like a fast-food franchise) and easy to pick up. This might make you think that the convenience factor in many commercial dog foods is much higher than their desire to provide the ultimate nutrition, and you would be right.  Because if nutrition was purely the priority your dog would be getting 80% plus meat and animal products and not the usual 30% meat. And they would NOT be getting 30 to 40 ingredients you typically see in commercial dog food to make up for what that grain or vegetable meal lacks.",
    p3: "Prolonged loose stools in any animal is bad as it reduces the health of the intestine and its ability to extract nutrients.  This is where healthy meat-based dog treats can come into play. If your dog is NOT allergic to a meat, and you buy one of our many SINGLE INGREDIENT dog treats, then you know that diarrhea or constipation should not be caused by that treat.  You know that they are going to get a big easy to digest protein boost from the treat. AND the bonus, that properly dried healthy meat-based dog treats provide OVER raw meat, is the much lower possible pathogen load. The heating process basically kills virtually all of the extremely bad bacteria. This is one of the main reasons that many people prefer meat-based treats over raw meat diets. They get to provide the nutrition as well as playing it very safe with their dog. Dog Owners also know that their dog already gets about 70% vegetable matter in their commercial dog food, so adding more vegetable or grain based dog treats DO NOT provide any additional nutrition to their dog. They just look pretty to the owner. Glazed ‘doggy donut’ anyone? Absurd. The grain based treats also are likely to have a whole swathe of additives including sugar, salt, added oils, colouring or preservatives.  Whereas SINGLE ingredient properly dried healthy dog treat is SINGLE INGREDIENT and hence no additives that the dog can react badly to.",
    p4: "This equates to about 10% of the raw meat dog food feeder owners experiencing dog vomiting from time to time. Or maybe even just once. Dogs can vomit for a myriad of reasons, and in fact one of the deadliest common food related deaths is from BLOAT when dogs eat too many pellets and they swell up in the dog’s stomach essentially choking them. A raw diet or meat-based dog treats DON’T swell in size when you add water so they wont cause bloat.  The raw feeders vomiting might be from a pathogen load on meat if it was stored incorrectly. Sometimes dogs will vomit on raw because the fat content of the food was too high. But you can get that in commercial dog food too. Whatever the reason, most meat-based treat feeders report a low vomiting incidence to us. That might be because they value the treat and their dog and restrict how much the dog eats in one session, or they are sure that their dog is not allergic to the treat, or that the treat has been cooked and has a very low chance of pathogen issues. Any way you look at it, vomiting should NOT be increased by cooking meat used in treats. If your dog vomits it is often from enjoying and eating the treat too fast. However, that rare chance is typically far outweigh by the increased nutrient value they get in meat treats (quality amino acids).",
    },
]

export default blogContent;